/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.AlumnoData;
import Data.InscripcionData;
import Data.MateriaData;
import Modelo.Alumno;
import Modelo.Conexion;
import Modelo.Inscripcion;
import Modelo.Materia;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Romi
 */
public class frmiInscribirAlumnoMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmiInscribirAlumnoMateria
     */
    public frmiInscribirAlumnoMateria() {
        initComponents();
        cargarCbo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboMateria = new javax.swing.JComboBox<>();
        cboAlumno = new javax.swing.JComboBox<>();
        btnInscribir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setTitle("Inscribir Alumno a Materia");

        jLabel1.setText("Materia");

        jLabel2.setText("Alumno");

        cboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAlumnoActionPerformed(evt);
            }
        });

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboMateria, 0, 131, Short.MAX_VALUE)
                    .addComponent(cboAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnInscribir)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnVolver))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cargarCbo(){
        try {
            Conexion con=new Conexion();
            AlumnoData a=new AlumnoData(con);
            MateriaData m=new MateriaData(con);
            List<Alumno> alumnos= a.buscarTodosAlumnos();
            List<Materia> materias= m.buscarTodasMaterias();
            for (int i = 0; i < alumnos.size(); i++) {
                if(alumnos.get(i).isActivo()==true)
                cboAlumno.addItem(alumnos.get(i).toString());       
            }
            for (int i = 0; i < materias.size(); i++) {
                if(materias.get(i).isActivo()==true)
                cboMateria.addItem(materias.get(i).toString());
            }
             
                    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmiModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }

}
    private void cboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAlumnoActionPerformed
        try {
            Conexion con =new Conexion();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmiInscribirAlumnoMateria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboAlumnoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
            dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
           Conexion con;
        try {
            con = new Conexion();
           Alumno al=new Alumno();
           Materia ma=new Materia();
           InscripcionData ins= new InscripcionData(con);
            AlumnoData a=new AlumnoData(con);
            MateriaData m=new MateriaData(con);
            List<Alumno> alumnos= a.buscarTodosAlumnos();
            List<Materia> materias= m.buscarTodasMaterias();
        for (int i = 0; i < materias.size(); i++) {
            if(cboMateria.getSelectedItem().toString().equals(materias.get(i).toString())){
                ma=materias.get(i);
        }}
        for (int i = 0; i < alumnos.size(); i++) {
            
            if(cboAlumno.getSelectedItem().toString().equals(alumnos.get(i).toString())){
            al=alumnos.get(i);
        }}
         Inscripcion i=new Inscripcion(al,ma,0,true);
         
       ins.guardarInscripcion(i);
 } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmiInscribirAlumnoMateria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboAlumno;
    private javax.swing.JComboBox<String> cboMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
